#!/bin/sh

echo -n "Most    1000: "
./run.sh -eufm <es/words/1000.txt | tail -1
#echo -n "Oxfords 3000: "
#./run.sh -gufm <de/words/oxford_3000_keys/oxford3000_uniq.txt | tail -1
#echo -n "IELTS   4000: "
#./run.sh -gufm <words/ielts_general_4000/ielts_general_4000.txt | tail -1
#echo -n "TOEFL   5000: "
#./run.sh -gufm <words/toefl_5000.txt | tail -1
echo -n "Google 10000: "
./run.sh -eufm <es/words/10000.txt | tail -1



ls -l es/translations/ | wc -l
ls -l es/words/active/ | wc -l
ls -l es/sound/ | wc -l

if [ "$1" = "-a" ]
then
(
     for f in es/translations/*
     do
         (cat ${f} 2>/dev/null; echo;) | grep -v '(' | grep -v  ') '
     done
) | wc -l | xargs echo -n # remove \n 
echo " without (*), where *=n,v,adj,..."
fi

