#!/bin/sh

for f in translations/*; do
    if [ "$1" = "-w" ]; then
        WORD="`echo -n ${f} | sed "s/.*\///"`"  # remove translation/ part
        echo -n "$WORD"
        CHAR_NUM=`echo -n -e "$WORD" | wc -c`
        let TAB_NUM=CHAR_NUM/8

        while true; do
            if [[ "$TAB_NUM" -gt 3 ]]; then
	        break
            fi
            let TAB_NUM=TAB_NUM+1
            echo -n -e "\t"
        done
	echo -n " "

        if [ "$2" = "-p" ]; then
            echo -n -e "[""`cat phonetics/$WORD 2>/dev/null`""]\t"
        fi
    fi
    echo "`cat ${f} 2>/dev/null`" 
done 
