#!/bin/sh

echo -n "Most    1000: "
./run.sh -ufm <words/1000.txt | tail -1
echo -n "Oxfords 3000: "
./run.sh -ufm <words/oxford_3000_keys/oxford3000_uniq.txt | tail -1
echo -n "IELTS   4000: "
./run.sh -ufm <words/ielts_general_4000/ielts_general_4000.txt | tail -1
echo -n "TOEFL   5000: "
./run.sh -ufm <words/toefl_5000.txt | tail -1
echo -n "Google 10000: "
./run.sh -ufm <words/google-10000-english.txt | tail -1
echo -n "Google 20000: "
./run.sh -ufm <words/google-20000-english.txt | tail -1
echo -n "Google 30000: "
./run.sh -ufm <words/30000.txt | tail -1


ls -l translations/ | wc -l | xargs echo -n # remove \n
echo " translated"
ls -l words/active/ | wc -l | xargs echo -n
echo " active"
ls -l sound/ | wc -l | xargs echo -n
echo " sounded"

if [ "$1" = "-a" ]
then
(
    for f in translations/*
    do
        (cat ${f} 2>/dev/null; echo;) | grep -v '(' | grep -v  ') '
    done 
) | wc -l | xargs echo -n # remove \n 
echo " without (*), where *=n,v,adj,..."
fi


